[package]
name = "alert"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[features]
default = []

[dev-dependencies]
cli_test_dir = "0.1.1"

[dependencies]
clap = "2.24.1"
# Enable this by passing `--features "clippy"` to cargo.  Needs nightly Rust.
clippy = { version = "*", optional = true }
error-chain = "0.10.0"
env_logger = "0.4.2"
log = "0.3.7"
notify-rust = "3.3.1"
regex = "0.2.1"
reqwest = "0.5.2"
shell-escape = "0.1.3"
